# Generated by Django 2.0 on 2018-10-09 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='About_us',
        ),
    ]
