# Generated by Django 2.0 on 2018-10-09 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20181009_1314'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About_us',
            new_name='AboutUs',
        ),
    ]
