# Generated by Django 2.0 on 2018-10-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20181009_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact us', 'verbose_name_plural': 'Contact us'},
        ),
        migrations.AlterField(
            model_name='contactus',
            name='address',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='fb_link',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='fb_messenger_link',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='open_hours',
            field=models.CharField(max_length=40),
        ),
    ]
