# Generated by Django 2.0 on 2018-10-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20181009_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='phone_number',
            field=models.CharField(default='09498931328', max_length=20),
            preserve_default=False,
        ),
    ]
