# Generated by Django 2.0 on 2018-09-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20180924_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('bank_deposit', 'Bank Deposit')], default='--', max_length=120),
        ),
    ]
