# Generated by Django 2.0 on 2018-09-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('bank_deposit', 'Bank Deposit'), ('credit_card', 'Credit Card')], max_length=120, null=True),
        ),
    ]
