# Generated by Django 2.0 on 2018-09-26 17:09

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20180926_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('date_added', models.DateTimeField()),
                ('bdo_branch', models.CharField(blank=True, max_length=50)),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to=orders.models.upload_image_path)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('bank_deposit', 'Bank Deposit'), ('credit_card', 'Credit Card')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('not_shipped', 'Not yet shipped'), ('shipped', 'Shipped')], default='not_shipped', max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('canceled', 'Canceled'), ('waiting_for_payment', 'Waiting for payment'), ('created', 'Created'), ('paid', 'Paid')], default='created', max_length=120),
        ),
    ]
