# Generated by Django 2.0 on 2018-09-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20180927_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('bank_deposit', 'Bank Deposit')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('waiting_for_payment', 'Waiting for payment'), ('paid', 'Paid'), ('canceled', 'Canceled')], default='created', max_length=120),
        ),
        migrations.AlterField(
            model_name='paymentconfirmation',
            name='email',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
