# Generated by Django 2.0 on 2018-09-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20180927_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('bank_deposit', 'Bank Deposit'), ('credit_card', 'Credit Card')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('not_shipped', 'Not yet shipped')], default='not_shipped', max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('canceled', 'Canceled'), ('created', 'Created'), ('waiting_for_payment', 'Waiting for payment')], default='created', max_length=120),
        ),
        migrations.AlterField(
            model_name='paymentconfirmation',
            name='date_added',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentconfirmation',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
