# Generated by Django 2.0 on 2018-09-26 17:40

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20180927_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('not_shipped', 'Not yet shipped'), ('shipped', 'Shipped')], default='not_shipped', max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('waiting_for_payment', 'Waiting for payment'), ('paid', 'Paid'), ('canceled', 'Canceled')], default='created', max_length=120),
        ),
        migrations.AlterField(
            model_name='paymentconfirmation',
            name='image',
            field=models.ImageField(upload_to=orders.models.upload_image_path),
        ),
    ]
