# Generated by Django 2.0 on 2018-09-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20180927_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email_shipping_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('canceled', 'Canceled'), ('waiting_for_payment', 'Waiting for payment'), ('created', 'Created'), ('paid', 'Paid')], default='created', max_length=120),
        ),
    ]
