# Generated by Django 2.0 on 2018-09-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20180928_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('not_shipped', 'Not yet shipped')], default='not_shipped', max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('waiting_for_payment', 'Waiting for payment'), ('paid', 'Paid'), ('canceled', 'Canceled')], default='created', max_length=120),
        ),
    ]
