# Generated by Django 2.0 on 2018-09-28 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20180929_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('bank_deposit', 'Bank Deposit')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting_for_payment', 'Waiting for payment'), ('paid', 'Paid'), ('created', 'Created'), ('canceled', 'Canceled')], default='created', max_length=120),
        ),
    ]
