# Generated by Django 2.0 on 2018-10-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20180929_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('not_shipped', 'Not yet shipped'), ('shipped', 'Shipped')], default='not_shipped', max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('canceled', 'Canceled'), ('paid', 'Paid'), ('created', 'Created'), ('waiting_for_payment', 'Waiting for payment')], default='created', max_length=120),
        ),
    ]
