# Generated by Django 2.0 on 2018-10-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20181009_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('waiting_for_payment', 'Waiting for payment'), ('paid', 'Paid'), ('canceled', 'Canceled')], default='created', max_length=120),
        ),
    ]
