# Generated by Django 2.0 on 2018-10-09 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_auto_20181009_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('shipped', 'Shipped'), ('not_shipped', 'Not yet shipped')], default='not_shipped', max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('created', 'Created'), ('waiting_for_payment', 'Waiting for payment'), ('canceled', 'Canceled')], default='created', max_length=120),
        ),
    ]
