# Generated by Django 2.0 on 2018-10-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_auto_20181009_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('bank_deposit', 'Bank Deposit'), ('credit_card', 'Credit Card')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('waiting_for_payment', 'Waiting for payment'), ('created', 'Created'), ('canceled', 'Canceled')], default='created', max_length=120),
        ),
    ]
