# Generated by Django 2.0 on 2018-10-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20181009_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('bank_deposit', 'Bank Deposit')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('waiting_for_payment', 'Waiting for payment'), ('canceled', 'Canceled'), ('created', 'Created')], default='created', max_length=120),
        ),
    ]
