# Generated by Django 2.0 on 2018-10-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_auto_20181009_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting_for_payment', 'Waiting for payment'), ('paid', 'Paid'), ('canceled', 'Canceled'), ('created', 'Created')], default='created', max_length=120),
        ),
    ]
