# Generated by Django 2.0 on 2018-10-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_auto_20181009_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('canceled', 'Canceled'), ('paid', 'Paid'), ('waiting_for_payment', 'Waiting for payment'), ('created', 'Created')], default='created', max_length=120),
        ),
    ]
