# Generated by Django 2.0 on 2018-10-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_auto_20181010_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('credit_card', 'Credit Card'), ('bank_deposit', 'Bank Deposit')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('canceled', 'Canceled'), ('paid', 'Paid'), ('waiting_for_payment', 'Waiting for payment')], default='created', max_length=120),
        ),
    ]
