# Generated by Django 2.0 on 2018-10-13 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_auto_20181013_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('bank_deposit', 'Bank Deposit'), ('credit_card', 'Credit Card')], max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('canceled', 'Canceled'), ('paid', 'Paid'), ('created', 'Created'), ('waiting_for_payment', 'Waiting for payment')], default='created', max_length=120),
        ),
    ]
