# Generated by Django 2.0 on 2018-10-15 05:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_auto_20181014_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('not_shipped', 'Not yet shipped'), ('shipped', 'Shipped')], default='not_shipped', max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('canceled', 'Canceled'), ('created', 'Created'), ('waiting_for_payment', 'Waiting for payment')], default='created', max_length=120),
        ),
    ]
