# Generated by Django 2.0 on 2018-07-31 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_subcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='name',
            new_name='subcategory',
        ),
    ]
