# Generated by Django 2.0 on 2018-08-01 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20180801_0123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='subcategory',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
    ]
